### PR TITLE
feat: implement users logic

### PR DESCRIPTION
**Pull request by JorgeAbelSousa**

### CODE REVIEW

**Review by suenefuzzo — CHANGES_REQUESTED** [review]
change model logic to user

**Review by Claudinier576 — CHANGES_REQUESTED** [review]
change User Model, remove is_colaborator and is_student

**Review by Claudinier576 — APPROVED** [review]

**Review by jullesss — CHANGES_REQUESTED** [review]
em UserDetailView,  permission_classes deve ser permissions.IsOwner e em UserView deve ser permissions.IsAdminUser.

**Review by jullesss — APPROVED** [review]

**Review by Claudinier576 — APPROVED** [review]

**Review by JorgeAbelSousa — COMMENTED** [review]
Verified

**Review by JorgeAbelSousa — COMMENTED** [review]
Changes verified

**Comment by JorgeAbelSousa** [comment]
> change model logic to user

Done

**Review by suenefuzzo — APPROVED** [review]

**Pull request merged**
